import nltk 
 '''
★ Write a function that takes a grammar (such as the one defined in
3.1) and returns a random sentence generated by the grammar.
(Use grammar.start() to find the start symbol of the grammar;
grammar.productions(lhs) to get the list of productions from the grammar
that have the specified left-hand side; and production.rhs() to get
the right-hand side of a production.)
'''
